### ISSUE TITLE
How to make configuration for category pagination?

### ISSUE THREAD

**Issue by dbarobin** [jekyll/jekyll-paginate#18]
I have installed the plugin `jekyll-paginate`, and read the `Usage`.

The usage said:

> **Usage**
> Once the gem is installed on your system, Jekyll will auto-require it. Just set the following configuration.

This doc did not express clearly. Thus I don't know how to set configuration. Could you help me?

Thanks! Have a nice day.

**Comment by parkr** [comment]
Check out jekyllrb.com/docs/pagination/ . We'll update the docs here. No category pagination at the moment, just posts.

**Comment by dbarobin** [comment]
Thanks a lot! Looking forward to add this feature.

**Comment by carloscarcamo** [comment]
is there any progress on this feature?
