### ISSUE TITLE
Pagination doesn't generate page directories when permalink is set

### ISSUE THREAD

**Issue by gabelevi** [jekyll/jekyll-paginate#25]
(Issue copied from https://github.com/jekyll/jekyll/issues/3471)

This tripped me up for 30 mins or so. I was trying to paginate `/blog/index.html`, but I had `permalink: /blog` set (I'm a n00b and I don't know what I'm doing). I did have `paginate_path set` correctly. The result was that visiting `/blog` would always start on the last page of pagination and be unable to find the other pages. None of the `/blog/pageN/directories` were generated.

In retrospect I can kind of understand what's going on. I suppose jekyll wanted to write `_site/blog/page2/index.html`, but permalink overrode it to write `_site/blog/index.html`, so each page was written to the same file. Perhaps an error when you keep overwriting the same file would help n00bs like me!

**Comment by gabelevi** [comment]
Ah sorry for the dupe...I checked the issues before filing but didn't check the duplicates. Glad it's getting fixed!

**Comment by corysimmons** [comment]
This tripped me up for around 30 mins as well. Can someone please update the docs here to express this warning? http://jekyllrb.com/docs/pagination/

**Comment by parkr** [comment]
@corysimmons Would you be able to submit a pull request? That page is here: https://github.com/jekyll/jekyll/blob/master/site/_docs/pagination.md
