### ISSUE TITLE
   Track time New issue Pagination when the index.html has had its name changed

### ISSUE THREAD

**Issue by knoxxs** [jekyll/jekyll-paginate#29]
Hey guys,

I changed the name of `index.html` file to `01-index.html` to give order to my pages.

Whenever I try and paginate it says ' Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination'.

How would one fix this?

**Comment by parkr** [comment]
Unfortunately, this plugin only allows you to use `index.html`.
