### ISSUE TITLE
Paginate Collections

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll-paginate#3]
Allow users to paginate collections!

**Comment by swashcap** [comment]
:+1:

**Comment by dseeman** [comment]
+1 for the solution proposed by @jeromecoupe (kudos to @sambaldwin for an easy work-around but I'm 100% in favor of making this a more universal feature)

**Comment by bjfish** [comment]
:+1:

**Comment by rachelnabors** [comment]
:+1:

**Comment by jorgebg** [comment]
:+1:

**Comment by rhewitt22** [comment]
:+1:

**Comment by TWiStErRob** [comment]
@parkr why was this closed? Where's the work on collection pagination, if any, being tracked in future?

**Comment by stammy** [comment]
Add me as interested in this as well :)

**Comment by rachelnabors** [comment]
And me.


  [image: photo]
*Rachel Nabors*
Storycoder, speaker, founder, Tin Magpie
 w:rachelnabors.com
 <http://twitter.com/rachelnabors>  <http://dribbble.com/rachelthegreat>
<http://plus.google.com/u/0/+RachelNabors>
<http://linkedin.com/in/rachelnabors>
  ------------------------------
*Speaking & Workshops in 2015*

   - Aug 26–27 UX Week, San Francisco
   <http://uxweek.com/speakers/web-animations-expert-tin-magpie-and-web-animation-weekly>
Animation
   and Motion Design: in Process, in Practice workshop
   <http://uxweek.com/workshops/animation-and-motion-design-in-process-in-practice>
   - Oct 28–30 FOWD, San Francisco
   <https://futureofwebdesign.com/san-francisco-2015> & Motion Design with
   CSS workshop
   <https://futureofwebdesign.com/san-francisco-2015/schedule/workshops/2068>

 Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=>

On Sat, Jul 25, 2015 at 4:37 PM Paul Stamatiou <notifications@github.com>
wrote:

> Add me as interested in this as well :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jekyll/jekyll-paginate/issues/3#issuecomment-124914990>
> .
>
-- 

   - Aug 26 –27UX Week, San Francisco
   - Oct 28 –30Future of Web Design, San Francisco, Motion Design with CSS
   workshop

  [image: photo]
*Rachel Nabors*
Storycoder, speaker, founder, Tin Magpie
 w:rachelnabors.com
 <http://twitter.com/rachelnabors>  <http://dribbble.com/rachelthegreat>
<http://plus.google.com/u/0/+RachelNabors>
<http://linkedin.com/in/rachelnabors>
  ------------------------------
*Speaking & Workshops in 2015*

   - Aug 26–27 UX Week, San Francisco
   <http://uxweek.com/speakers/web-animations-expert-tin-magpie-and-web-animation-weekly>
Animation
   and Motion Design: in Process, in Practice workshop
   <http://uxweek.com/workshops/animation-and-motion-design-in-process-in-practice>
   - Oct 28–30 FOWD, San Francisco
   <https://futureofwebdesign.com/san-francisco-2015> & Motion Design with
   CSS workshop
   <https://futureofwebdesign.com/san-francisco-2015/schedule/workshops/2068>

 Get a signature like this:
<https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>

**Comment by sarhov** [comment]
I also didn't understand why the issue is closed ...

**Comment by gynter** [comment]
Because `jekyll-paginate` will be discontinued, more info in [forum](https://talk.jekyllrb.com/t/announcement-retiring-jekyll-paginate/1004).

**Comment by TWiStErRob** [comment]
Thanks @gynter, please note that the issue was closed a month ago, while that announcement was done 10 hours ago. So it's clear now it, but we can agree it was a weird timeline of communication.
It would be nice to update the README.md with a deprecation notice with a link to that forum and later a link to replacement, thanks again!

**Comment by Fallenstedt** [comment]
You can include pagination by including some liquid logic into the _layout_ of your collection. 
For example, I have a collection called "_portfolios" where I will hold all of my portfolio items. Each portfolio item has yml like this: 

`---
title: Landscape
subtitle: Photography
layout: portfolio

cta:
  btnText: View Services
  btnType: btn-warning
  btnLink: /about/

images:
- /images/landscape/landscape-8.jpg
- /images/landscape/landscape-4.jpg
- /images/landscape/landscape-1.jpg
- /images/landscape/landscape-2.jpg
- /images/landscape/landscape-3.jpg
---`

In `layouts > portfolio.html` I have the following includes to use a widget I made: 

` {% include collection-pagination.html collection="portfolios" %}`


The liquid logic in collection-pagination.html is: 

`
{% assign this_collection = include.collection %}
{% for c in site.[this_collection] %}
{% if c.title == page.title %}
  {% assign thisPost = c %}
  {% if forloop.index == 1 %}
    {% assign prevflag = 0 %}
    {% assign nextflag = 1 %}
  {% elsif forloop.index == forloop.length %}
    {% assign prevflag = 1 %}
    {% assign nextflag = 0 %}
  {% else %}
    {% assign prevflag = 1 %}
    {% assign nextflag = 1 %}
  {% endif %}
{% endif %}
{% endfor %}

{% for c in site.[this_collection] %}
  {% if c.title == page.title %}
    {% assign prevflag = 0 %}
  {% endif %}
  {% if prevflag == 1 %}
    {% assign prevPost = c %}
    {% assign page.previous = c %}
  {% endif %}
{% endfor %}

{% if nextflag == 1 %}
  {% for c in site.[this_collection] %}
    {% if foundPost == 1 %}
      {% assign getNext = 1 %}
    {% endif %}
    {% if c.title == page.title %}
      {% assign foundPost = 1 %}
    {% endif %}
    {% if getNext == 1%}
      {% assign nextPost = c %}
      {% assign page.next = c %}
      {% assign foundPost = 0 %}
      {% assign getNext = 0 %}
    {% endif %}
  {% endfor %}
{% endif %}


<div class="collective-navigation">
  {% if prevPost.url %}
    <a title="{{ prevPost.title }}" href="{{ prevPost.url }}"><i class="prev" aria-hidden="true"></i>previous</a>
  {% endif %}

  {% if nextPost.url %}
    <a title="{{ nextPost.title }}" href="{{ nextPost.url }}"><i class="next" aria-hidden="true"></i>next</a>
  {% endif %}
</div>
`

This generate two buttons that you can style. The neat part is that if you are at the first item of the collection, the "previous" button will be disabled and hidden. If you are at the last item of a collection, the "next" button will be disabled.

I learned about this from: anjesh.github.io/2015/01/25/collection-pagination-working-github-pages/

**Comment by weevil** [comment]
I've been trying to paginate a masonry layout image-board that iterates through every file in an image folder and it feels way more complicated than it should be... I've been using paginate v2

**Comment by ashmaroli** [comment]
@weevil Paginate v2 is a different project entirely:
https://github.com/sverrirs/jekyll-paginate-v2
