### ISSUE TITLE
Now available: New Pagination Plugin (Fully backwards compatible)

### ISSUE THREAD

**Issue by sverrirs** [jekyll/jekyll-paginate#36]
Posting here since none of the open issues are getting any real replies and people seem to still be frustrated about the decommissioning of this gem. 

I've recently re-written the pagination plugin which I hope is a viable alternative to the old one. It is fully backwards compatible and supports a slew of new frequently requested features. 

Check it out, I'd really welcome more testers :)
https://github.com/sverrirs/jekyll-paginate-v2

**Comment by Stargator** [comment]
Hopefully @parkr or @benbalter can chime in on this.

I read in the other thread #27 that you did this as a product of working for a client. I don't know what hoops your project may have to go through, but I'd imagine these two would be able to provide insight into how possible it may be.

Since this project doesn't have any active contributers/owners, you and anyone else interested may want to consider taking up the reins.

**Comment by sverrirs** [comment]
Hi @parkr, @benbalter, @Stargator and anyone else listening,

I am confident that the new pagination code is ready for a real prime-time test. As of now the gem version is at 1.4.0. https://github.com/sverrirs/jekyll-paginate-v2

The code is documented and contains working example sites for users. The gem is designed to act as a zero-config replacement for the old one and requires no additional changes to achieve this. All sites should just work (apart from changing `jekyll-paginate` to `jekyll-paginate-v2`).

Completing the unit-tests coverage is now the primary focus and it is progressing well. 

I haven't really had any real bug-feedback in the issues section and that worries me a little bit (there are at least a few people using this gem I think). 

A controlled real-world test of this logic would be fantastic at this point and I would welcome any-and-all help you or anyone else can give me to run this gem on a good set of existing jekyll websites of various complexities that are representative of what can be found in the wild.

Also general comments and thoughts on the code, structure and design would be most welcome .

**Comment by parkr** [comment]
I'm replying over here: https://github.com/sverrirs/jekyll-paginate-v2/issues/9
