### ISSUE TITLE
Allow to exclude certain categories from paginated posts

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll-paginate#6]
See https://github.com/jekyll/jekyll/issues/2018 for more

**Comment by djacquel** [comment]
Note: any post that have `hidden: true` in his front matter is ignored from pagination. And from what I saw in the code, it's the only use of this variable.

**Comment by djacquel** [comment]
Ok Specs are here. Hope ready for Jekyll 3.0 FTW!

**Comment by duanefields** [comment]
```
module Jekyll
  module ExceptFilter
    # Filter an array of objects, inverse of where
    #
    # input - the object array
    # property - property within each object to filter by
    # value - value to filter out
    #
    # Returns the filtered array of objects
    def except(input, property, value)
      return input unless input.is_a?(Enumerable)
      input = input.values if input.is_a?(Hash)
      input.select { |object| item_property(object, property) != value }
    end
  end
end

Liquid::Template.register_filter(Jekyll::ExceptFilter)

**Comment by drinkbird** [comment]
Thanks @djacquel for pointing out the `hidden` option

**Comment by weevil** [comment]
Since exclude doesn't work yet, is it possible to give the pagination: front matter multiple categories? I want all posts to show on my main page except for one category.

**Comment by rampatra** [comment]
Adding `hidden: true` works. The posts that have this don't show up. However, I think `paginator.total_pages` still considers these posts. Is this a bug or am I missing something?

**Comment by askel45** [comment]
> Since exclude doesn't work yet, is it possible to give the pagination: front matter multiple categories? I want all posts to show on my main page except for one category.

Me too. Using `hidden: true` hides the post both from the homepage and the category pages (I am using Jekyll Paginate v2)
